name: Autogenerate doc/legendary.txt
on:
  push:
    branches: [ master ]
jobs:
  gen-docs:
    name: Autogenerate doc/legendary.txt
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup git
        run: |
          git config --local user.email "<>"
          git config --local user.name "github-actions[bot]"
          printf 'VIMDOC_BRANCH=bot/vimdoc/%s\n' ${GITHUB_REF#refs/heads/} >> $GITHUB_ENV
      - name: Checkout to vimdoc branch
        run: git checkout -b ${VIMDOC_BRANCH}
      - name: panvimdoc
        uses: kdheepak/panvimdoc@v2.7.1
        with:
          vimdoc: legendary
          description: keymaps - commands - autocmds
          pandoc:
            - ./README.md
            - ./doc/table_structures/README.md
            - ./doc/table_structures/KEYMAPS.md
            - ./doc/table_structures/COMMANDS.md
            - ./doc/table_structures/FUNCTIONS.md
            - ./doc/table_structures/AUTOCMDS.md
            - ./doc/API.md
            - ./doc/MAPPING_DEVELOPMENT.md
            - ./doc/USAGE_EXAMPLES.md
            - ./doc/WHICH_KEY.md
      - name: Create PR
        run: |
          if ! [[ -z $(git status -s) ]]; then
            git add doc/legendary.txt
            git commit -m "chore: generated vimdoc"
            git push --force https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY} ${VIMDOC_BRANCH}
            gh pr create --fill --base ${GITHUB_REF#refs/heads/} --head ${VIMDOC_BRANCH} || true
          fi
